#%RAML 1.0
title: hello-service REST API
version: 1.0.0
description: |
  hello world project, with RESTful api, built with spring boot.
types:
  Decimal:
    description: |
      decimal number: a numeric value with precise decimal places
      (instead of floating-point based).
  LocalDate:
    description: date without time, formatted like this `2017-10-24`.
  DateTime:
    description: instant of time without time zone concept.
  ErrorDto:
    type: object
    example: |
      {
        "errorCode": "ACCESS_DENIED"
      }
  People:
    type: object
    examples:
      general: |
        {
          "id": 10,
          "version": 1,
          "creationDate": "2018-06-09T12:38:56Z",
          "firstName": "Coriss",
          "lastName": "Morse",
          "gender": "MALE",
          "dateOfBirth": "1986-08-25"
        }
  Family:
    type: object
    examples:
      general: |
        {
          "id": 2,
          "version": 1,
          "creationDate": "2018-06-09T15:54:04Z",
          "father": {
            "id": 10,
            "version": 1,
            "creationDate": "2018-06-09T12:38:56Z",
            "firstName": "Coriss",
            "lastName": "Morse",
            "gender": "MALE",
            "dateOfBirth": "1986-08-25"
          },
          "mother": {
            "id": 11,
            "version": 1,
            "creationDate": "2018-06-09T12:38:56Z",
            "firstName": "Teddie",
            "lastName": "Hancock",
            "gender": "FEMALE",
            "dateOfBirth": "2014-03-04"
          }
        }

baseUri: http://localhost:8080

/api:
  /1.1:
    /hello:
      /version:
        get:
          description: |
            serving the application version, for ease of health-checking.
          responses:
            200:
              body:
                application/json:
                  type: People
                  example: |
                    {
                        "currentTime": "2018-06-10T07:17:04.487Z",
                        "springProfiles": "default",
                        "serviceName": "hello-service"
                    }
      /people:
        get:
          queryParameters:
            page: integer
            limit: integer
          responses:
            200:
              body:
                application/json:
                  type: People[]
        post:
          body:
            application/json:
              type: People
          responses:
            200:
              body:
                application/json:
                  type: People
        /{id}:
          get:
            responses:
              200:
                body:
                  application/json:
                    type: People
          /addAge:
            put:
              responses:
                200:
                  body:
                    application/json:
                      type: People
          /wife:
            get:
          /husband:
            get:
          /asFather:
            /family:
              get:
      /family:
        /{id}:
          get:
      /justAnotherWomen:
        get:
          responses:
            200:
              body:
                application/json:
                  type: People
      /aFewPeople:
        get:
          responses:
            200:
              body:
                application/json:
                  type: People[]
      /aMan:
        get:
          responses:
            200:
              body:
                application/json:
                  type: object
      /firstMan:
        get:
          responses:
            200:
              body:
                application/json:
                  type: People
