apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  namespace: hello-world
  name: people-service-config
  labels:
    type: conf
data:
  "application.yaml": |
    server.port: 8082
    spring:
      datasource:
        url: jdbc:mysql://hellodb:3306/hellodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true
        username: ppl_dbuser
        password: pass1234
    auth-service:
      jwt:
        public-key-PEM:
          -----BEGIN PUBLIC KEY-----
          MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+Ft3AzB+xBNaoBOYU0fj3+mAnrM+aYIA
          8MVZV/s28qH6mGcUfrqGnKMu7t+EVmTP0f3RGOd6sO1AnhsqkLzCrQ==
          -----END PUBLIC KEY-----
    people-service:
      options:
        enable-debug-endpoint: false
        accept-expired-auth-token: false
        disable-permission-check: false