apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  namespace: hello-world
  name: javaplay-logger-config
  labels:
    type: conf
data:
  "logback.xml": |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

      <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
      <property name="LOG_PATTERN"
                value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(${LOG_LEVEL_PATTERN:-%5p}) %gray( --- [%12thread]) %cyan(%-38logger{36}.%M):%L : %msg%n"/>

      <appender name="sout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>${LOG_PATTERN}</pattern>
        </encoder>
      </appender>

      <appender name="general" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>./log/javaplay.log</file>

        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
          <fileNamePattern>./logs/javaplay.%i.log</fileNamePattern>
          <minIndex>0</minIndex>
          <maxIndex>9</maxIndex>
        </rollingPolicy>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
          <maxFileSize>16MB</maxFileSize>
        </triggeringPolicy>

        <encoder>
          <pattern>${LOG_PATTERN}</pattern>
        </encoder>
      </appender>

      <root level="info">
        <appender-ref ref="sout" />
        <appender-ref ref="general" />
      </root>

    </configuration>