apiVersion: v1
kind: PersistentVolume
metadata:
  name: hellodb-vol
  labels:
    type: pv
    app: "hellodb"
    format: "mysql"
    tier: db
    env: debug
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # for ease of local debugging, use "Retain"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /Users/Shared/k8s-volumes/hellodb-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hello-world
  name: hellodb-vol-claim
  labels:
    app: hellodb
    format: mysql
    tier: db
    env: debug
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app: "hellodb"
      format: "mysql"
      tier: db
      env: debug
