server.port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hellodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&noAccessToProcedureBodies=true
    username: hellouser
    password: pass1234
    hikari:
      maximum-pool-size: 100
      connection-timeout: 6000
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

hello-service:
  service-name: hello-service
  api-version: 1.3
  # NEVER OVERRIDE THIS VALUE IN RUNTIME
  api-base-url: /api/1.3
  version-description: demo project for spring-boot.
  options:
    enable-debug-endpoint: true