apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  namespace: hello-world
  name: auth-service-config
  labels:
    type: conf
data:
  "application.yaml": |
    server.port: 8080
    spring:
      datasource:
        url: jdbc:mysql://hellodb:3306/hellodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true
        username: auth_dbuser
        password: pass1234

    auth-service:
      options:
        echo-login-info: false
        enable-debug-endpoint: true
        accept-expired-auth-token: false
      jwt:
        jws-algorithm-name: ES256K
        private-key-PEM:
          -----BEGIN PRIVATE KEY-----
          MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgjZ+mQMBI3V/BRfTM4Rx2
          0oiqtdUw7j6mPi5wg+AgROihRANCAAT4W3cDMH7EE1qgE5hTR+Pf6YCesz5pggDw
          xVlX+zbyofqYZxR+uoacoy7u34RWZM/R/dEY53qw7UCeGyqQvMKt
          -----END PRIVATE KEY-----
        public-key-PEM:
          -----BEGIN PUBLIC KEY-----
          MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+Ft3AzB+xBNaoBOYU0fj3+mAnrM+aYIA
          8MVZV/s28qH6mGcUfrqGnKMu7t+EVmTP0f3RGOd6sO1AnhsqkLzCrQ==
          -----END PUBLIC KEY-----
        token-valid-time-sec: 1500