apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-world
  name: nodeplay
  labels:
    app: nodeplay
    tier: app
    env: debug
spec:
  selector:
    matchLabels:
      app: nodeplay
      tier: app
      env: debug
  template:
    metadata:
      labels:
        app: nodeplay
        tier: app
        env: debug
    spec:
      containers:
        - name: node
          image: node:14-slim
          # workingDir: /usr/src/app/express-hello
          # command: [ "/usr/local/bin/node", "." ]
          command: [ "/bin/sh", "-c" ]
          args: ["cp -R /nodeplay /usr/src/app/ ; cd /usr/src/app/express-hello ; /usr/local/bin/node ."]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nodeplay-vol
              mountPath: /nodeplay
            - name: tool-vol
              mountPath: /tool
          resources:
            requests:
              cpu: "1000m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
      volumes:
        - name: nodeplay-vol
          persistentVolumeClaim:
            claimName: nodeplay-vol-claim
        - name: tool-vol
          persistentVolumeClaim:
            claimName: tool-vol-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-world
  name: nodeplay-service
  labels:
    app: nodeplay
    tier: app
    env: debug
spec:
  selector:
    app: nodeplay
    tier: app
    env: debug
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # the port that the app serving
