apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  namespace: hello-world
  name: mariadb-config-file
  labels:
    type: conf
data:
  my.cnf: |
    [mysqld]
    max_connections = 1500
    innodb_open_files	= 400
    innodb_io_capacity	= 400

    [mariadb]
    skip-host-cache
    skip-name-resolve